[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/academic-work"
  to = "/academic-research/"
  status = 301
  force = true

[[redirects]]
  from = "/academic-work/*"
  to = "/academic-research/"
  status = 301
  force = true

[[redirects]]
  from = "/research"
  to = "/academic-research/"
  status = 301
  force = true

[[redirects]]
  from = "/research/*"
  to = "/academic-research/"
  status = 301
  force = true
